### ISSUE TITLE
libbpf: ebpf-kill-example is out of sync with new interface

### ISSUE THREAD

**Issue by niclashedam** [niclashedam/ebpf-kill-example#11]
Libbpf has undergone several API changes recently. As such, `ebpf-kill-example` doesn't compile anymore.

**Comment by niclashedam** [comment]
@qmonnet I see that libbpf has changed quite a lot since I made this repository. Can you give me a few pointers on the best practice with libbpf 1.2 so I can update the repository accordingly?

**Comment by qmonnet** [comment]
The best that comes to mind would be https://nakryiko.com/posts/libbpf-v1/

**Comment by niclashedam** [comment]
Thank you so much for the link.
I have finally had time to work on this. If you have time, I would love to hear if you have any comments on #12.
